kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-config
data:
  ROLE_ARN_CLUSTER_AUTOSCALER: arn:aws:iam::863518836478:role/dev-kf13_cluster-autoscaler
  ROLE_ARN_LOADBALANCER_INGRESS_CONTROLLER: arn:aws:iam::863518836478:role/my-eks-cluster_aws-alb-ingress-controller
  ROLE_ARN_EXTERNAL_DNS: arn:aws:iam::863518836478:role/dev-kf13_external-dns  
  ROLE_ARN_EXTERNAL_SECRETS: arn:aws:iam::863518836478:role/dev-kf13_external-secrets  
  CLUSTER_NAME: dev-kf13
  AWS_REGION: eu-central-1
  VPC_ID: vpc-038b1e8ba71bdbecf
  DOMAIN: dev-kf13.learn-mlops.com
  RDS_DB_NAME_CACHE: cachedb
  RDS_DB_NAME_PIPELINES:  mlpipeline
  RDS_DB_NAME_METADATA: metadb
  RDS_DB_NAME_KATIB: katib
  RDS_HOST: dev-kf13-instance.c6e2xeayekua.eu-central-1.rds.amazonaws.com
  RDS_PORT: 3306
  ARTIFACTS_S3_BUCKET: 863518836478-dev-kf13-kubeflow