apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: aws-secret
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::863518836478:role/dev-kf13_kubeflow_external-secrets-kubeflow
  data:
    - key: dev-kf13/kubeflow/rds_username
      name: RDS_USERNAME      
    - key: dev-kf13/kubeflow/rds_password
      name: RDS_PASSWORD
    - key: dev-kf13/kubeflow/s3_access_key
      name: S3_ACCESS_KEY
    - key: dev-kf13/kubeflow/s3_secret_key
      name: S3_SECRET_KEY