apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.1.6
    chart: aws-load-balancer-controller
    helm:
     parameters:
      - name: "rbac.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
        valueFrom:
            configMapKeyRef:
              name: aws-config
              key: ROLE_ARN_LOADBALANCER_INGRESS_CONTROLLER      
      - name: clusterName
        valueFrom:
            configMapKeyRef:
              name: aws-config
              key: CLUSTER_NAME
      - name: vpcId
        valueFrom:
            configMapKeyRef:
              name: aws-config
              key: VPC_ID
      - name: region
        valueFrom:
            configMapKeyRef:
              name: aws-config
              key: AWS_REGION
      - name: resources.limits.cpu
        value: 100m
      - name: resources.limits.memory
        value: 300Mi
      - name: resources.requests.cpu
        value: 100m
      - name: resources.requests.memory
        value: 300Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true